spring.application.name=SocialMediaApp

logging.level.org.springframework.web.filter.CorsFilter=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web.cors=DEBUG
